spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: kim-springcloud-config-test-devv
---
spring:
  profiles: default
  application:
    name: kim-springcloud-config-test-default