spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: kim-springcloud-config-client333

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:admin@localhost:7301/eureka
  register-with-eureka: false

info:
  app.name: kim-springcloud-config-client-dev123
  company.name: kim123
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: kim-springcloud-config-test-client2

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:admin@localhost:7301/eureka
  register-with-eureka: false
  
info:
  app.name: kim-springcloud-config-client-beta2
  company.name: kim2