spring:
   profiles:
      active:
        - dev
---
server:
  port: 7001

spring:
  profiles: dev
  application:
      name: kim-springcloud-config-eureka-client
eureka:
 server:
  eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  enable-self-preservation: false #设置为false表示关闭保护模式
 client:
  fetch-registry: false
  register-with-eureka: false
  serviceUrl:
    defaultZone: http://admin:admin@localhost:7001/eureka
info:
  app.name: kim-springcloud-config-eureka-client-dev
  company.name: kim
---
server:
  port: 7002

spring:
  profiles: beta
  application:
      name: kim-springcloud-config-eureka-client2

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:admin@localhost:7002/eureka
  register-with-eureka: false
  
info:
  app.name: kim-springcloud-config-eureka-client-beta2
  company.name: kim2