spring:
   profiles:
      active:
        - dev
---
server:
  port: 7001

spring:
  profiles: dev
  application:
      name: kim-springcloud-config-eureka-client
eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:admin@localhost:7001/eureka
  register-with-eureka: false

info:
  app.name: kim-springcloud-config-eureka-client-dev
  company.name: kim
---
server:
  port: 7002

spring:
  profiles: beta
  application:
      name: kim-springcloud-config-eureka-client2

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:admin@localhost:7002/eureka
  register-with-eureka: false
  
info:
  app.name: kim-springcloud-config-eureka-client-beta2
  company.name: kim2